# Travis Continuous Integration Configuration File
language:
  - cpp
compiler:
  - gcc
notifications:
  email:
    recipients:
      - otamachan@gmail.com
    on_success: always #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
before_install: # Use this to prepare the system to install prerequisites or dependencies
  # Define some config vars
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
  - sudo apt-get install -qq -y subversion gcc g++ libjpeg-dev libxext-dev libx11-dev libgl1-mesa-dev libglu1-mesa-dev libpq-dev libpng12-dev xfonts-100dpi xfonts-75dpi msttcorefonts
install: # Use this to install any prerequisites or dependencies necessary to run your build
  - cd ${HOME}
  - git clone http://github.com/euslisp/jskeus jskeus
  - ln -s $CI_SOURCE_PATH jskeus/eus
script: # All commands must exit with code 0 on success. Anything else is considered failure.
  - cd jskeus
  - make
  - source bashrc.eus
  - irteusgl irteus/demo/demo.l "(defmacro do-until-key (&rest bodies) \`(dotimes (i 10) ,@bodies))" "(full-body-ik)" "(quit)"
  - irteusgl irteus/demo/demo.l "(defmacro do-until-key (&rest bodies) \`(dotimes (i 10) ,@bodies))" "(dual-arm-ik)" "(quit)"
  - irteusgl irteus/demo/demo.l "(defmacro do-until-key (&rest bodies) \`(dotimes (i 10) ,@bodies))" "(hand-grasp)" "(quit)"
  - irteusgl irteus/demo/demo.l "(defmacro do-until-key (&rest bodies) \`(dotimes (i 10) ,@bodies))" "(dual-manip-ik)" "(quit)"
  - irteusgl irteus/demo/demo.l "(defmacro do-until-key (&rest bodies) \`(dotimes (i 10) ,@bodies))" "(crank-motion)" "(quit)"
  - irteusgl irteus/demo/demo.l "(defmacro do-until-key (&rest bodies) \`(dotimes (i 10) ,@bodies))" "(walk-motion-for-sample-robot)" "(quit)"
  - irteusgl irteus/demo/demo.l "(defmacro do-until-key (&rest bodies) \`(dotimes (i 10) ,@bodies))" "(trot-walk-motion-for-sample-robot)" "(quit)"
  - irteusgl irteus/demo/demo.l "(defmacro do-until-key (&rest bodies) \`(dotimes (i 10) ,@bodies))" "(crawl-walk-motion-for-sample-robot)" "(quit)"
  - irteusgl irteus/demo/demo.l "(defmacro do-until-key (&rest bodies) \`(dotimes (i 10) ,@bodies))" "(walk-motion-for-robots)" "(quit)"
  - irteusgl irteus/demo/demo.l "(defmacro do-until-key (&rest bodies) \`(dotimes (i 10) ,@bodies))" "(hanoi-arm)" "(quit)"
  - irteusgl irteus/demo/demo.l "(defmacro do-until-key (&rest bodies) \`(dotimes (i 10) ,@bodies))" "(particle)" "(quit)"
after_failure:
  - echo "failure"

